
FROM node:20 AS builder

# Đặt thư mục làm việc
WORKDIR /app

# Sao chép file package.json và package-lock.json trước để cache dependencies
COPY package*.json ./

# Cài đặt dependencies
RUN npm ci --only=production --legacy-peer-deps


# Sao chép toàn bộ source code
COPY . .

# Build ứng dụng
RUN npm run build

# Sử dụng Nginx chạy frontend
FROM nginx:alpine

# Copy file build sang Nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Mở cổng 80
EXPOSE 80

# Chạy Nginx
CMD ["nginx", "-g", "daemon off;"]
