# Sử dụng Node.js phiên bản phù hợp
FROM node:20

# Đặt thư mục làm việc
WORKDIR /app

# Sao chép file package.json và package-lock.json
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Sao chép toàn bộ source code
COPY . .


EXPOSE 4000

# Chạy ứng dụng
CMD ["npm", "start"]
